#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/samba/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# wmnd &
# wmsmixer -w &
#/usr/bin/statnot &
#/usr/bin/notification-daemon &
#xfce4-power-manager &
#sudo /usr/bin/vendor_perl/spamd &
batti &
conky &
nm-applet &
xscreensaver -no-splash &
udiskie -2&
#~/.bin/mailcheck &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# exec fluxbox
# or if you want to keep a log:
exec fluxbox -log "~/.fluxbox/log"
