#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/samba/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# wmnd &
# wmsmixer -w &
#/usr/lib/notification-daemon-1.0/notification-daemon 2>&1 >> /home/samba/notifications.log &
#/usr/bin/statnot &
#xfce4-power-manager &
xscreensaver -no-splash &
conky &
~/.bin/mailcheck &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# exec fluxbox
# or if you want to keep a log:
exec fluxbox -log "/home/samba/.fluxbox/log"
