#!/usr/bin/python2.7
# Author: Preziusi Roberto
# Description: Easy DNS Changer
# License GPLv3
import logging as log

def getargs():
	import argparse,sys
	p = argparse.ArgumentParser()
	p.add_argument("-w","--work",action="store_true",help="Set work DNS ")
	p.add_argument("-c","--casa",action="store_true",help="Set home DNS")
	p.add_argument("-a","--append",help="Append specified IP to dns file")
	p.add_argument("-f","--free",action="store_true",help="Set Google and Level3 DNS")
	p.add_argument("-o","--opendns",action="store_true",help="Set OpenDNS")
	p.add_argument("-l","--list",action="store_true",help="List all available DNS type")
	p.add_argument("-s","--show",action="store_true",help="Show DNS file settings")
	p.add_argument("-v","--verbose",action="count",help="Set verbosity")
	#argv="-a".split()
	opt = p.parse_args()
	if len(sys.argv)==1:
		dns_show()
	return opt

def dns_defs():
	ldns=dict()
	ldns["generic_ns1"]="8.8.8.8"
	ldns["generic_ns2"]="4.2.2.4"
	ldns["work_ns1"]="172.20.23.1"
	ldns["work_ns2"]="172.20.23.2"
	ldns["casa_ns1"]="4.2.2.2"
	ldns["casa_ns2"]="192.168.1.254"
	ldns["free_ns1"]="8.8.4.4"
	ldns["free_ns2"]="4.2.2.2"
	ldns["open_ns1"]="208.67.222.222"
	ldns["open_ns2"]="208.67.220.220"
	return ldns

def dns_lists():
	import sys
	ldns = dns_defs()
	for dns,ip in ldns.items():
		print dns, "=", ip
	sys.exit()

def get_gw():
	import commands
	gw = commands.getoutput("route -n | grep ^0.0.0.0  | awk '{print $2}'")
	if opt.verbose:
		print "GW = ", gw
	return gw

def dns_setup(label,ns1,ns2="4.2.2.2",ns3 = "8.8.4.4",dnsfile="/etc/resolv.conf"):
	import commands
	
	if opt.verbose:
		print "debug1: ns1=", ns1
		print "debug1: ns2=", ns2

	mystring = """ ' # DDNS setup#\nnameserver %s\nnameserver %s\nnameserver %s'""" % ( ns1, ns2, ns3 ) 
	cmd = 'echo ' + mystring + ' | sudo tee %s ' % ( dnsfile )
	if opt.verbose:
		print "cmd :", cmd
	rs, outxt = commands.getstatusoutput(cmd)
	if rs<0:
		print "[ERROR]:\tSome error occurred"
	else:
		dns_show()
		print "[OK]: Set DNS = ", label

def dns_show(dnsfile="/etc/resolv.conf"):
	import sys
	with open(dnsfile,"r") as f:
		for line in f:
			print line,
	sys.exit()


if __name__ == "__main__":
	opt = getargs()
		
	if opt.list:
		dns_lists()
	if opt.show:
		dns_show()

	ldns=dns_defs()	

	if opt.work:
		label="work"
		ns1=ldns["work_ns1"]
		ns2=ldns["work_ns2"]

	if opt.casa:
		label="casa"
		ns1=ldns["casa_ns1"]
		ns2=ldns["casa_ns2"]

	if opt.free:
		label="free"
		ns1=ldns["free_ns1"]
		ns2=ldns["free_ns2"]

	if opt.opendns:
		label="opendns"
		ns1=ldns["open_ns1"]
		ns2=ldns["open_ns2"]
	
	if opt.append:
		label="append"
		ns2=opt.append
	
	dns_setup(label,ns1,ns2)			# write all in /etc/resolv.conf
		
