#!/bin/bash
# mailcheck
# TODO: convert in python
DELAY=60
MAILLOG=$HOME/.mailcheck.log
notify() {
  PMLOG="$HOME/.pmlog"
  if [ -f "$PMLOG" ]; then
    MSG="$(cat $PMLOG | mailstat -toms )"
	date '+%F %T' >> $MAILLOG
    cat $PMLOG >> $MAILLOG
	mv $PMLOG ${PMLOG}.old
    if [ -n "$MSG" ]; then
      notify-send -c email.arrived -i "/usr/share/icons/Neu/scalable/apps/email.svg" "New mail" "$MSG"
	  logger $MSG
	else
		echo "No new mail"
    fi
  fi
}

while true; do
 # $HOME/.bin/msmtp-runqueue.sh
	echo -e "\nChecking..."
	getmail -q --rcfile getmailrc &
	wait
	ping -c 1 8.8.8.8 2>&1 > /dev/null
	if [ $? ];then
		notify
		DELAY=900
	else
		echo "Offline -- not checked."
		DELAY=60
	fi
	echo Next check at $(date -d "$DELAY seconds" '+%F %T...')
	sleep $DELAY;
done

